### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by katglin** [advancedWeb2018/TMS_cources_2019#100]
- [x] empty catch block in InviteController

- [x] empty if block in RecoverPassword in AccountController

- [x] allow manager open settings and milestones pages with all their functionality available

- [x] On some of admin pages you are referencing Table.css file which is absent (look at console errors in browser)

![image](https://user-images.githubusercontent.com/17654862/56344568-62c4e300-61c6-11e9-9995-feede111ef68.png)

- [x] Team name length - set max length (maybe about 20 symbols?)

- [x] Task type field - set maxlength="15"

Layout fixes: 
- [x] some html elements (buttons) have right/left alignment but get out of borders

![image](https://user-images.githubusercontent.com/17654862/56343889-b9c9b880-61c4-11e9-8af4-5404f162826f.png)

- [x] links inside pages should look as buttons (/Task?TeamId=1 - "To team info", "To milestones")

- [x] Owner -> send invite -> message should be written in a textarea, not an input

- [x] task list/milestones wasnt available from Team/Info for everyone except owner

---
пока буду проходить чек лист могу что-то добавить/дополнить ссылками, не закрывай пока

**Comment by alexdp1996** [comment]
- [ ] task list/milestones wasnt available from Team/Info for everyone except owner

**Comment by katglin** [comment]
Suggestion
В EditStates btn-warning (Reset button) -> btn-info?

Layout bugs:
- [ ] Invites button layout on Members page
- [ ] Forget password label layout
- [ ]  Create task layout for mobile devices
