### ISSUE TITLE
Failed to delete task type

### ISSUE THREAD

**Issue by katglin** [advancedWeb2018/TMS_cources_2019#107]
Link to delete-method looks like "Delete/DeleteTaskType?..." and is most likely wrong

Delete/Delete - > Team/Delete

![image](https://user-images.githubusercontent.com/17654862/56342150-d6afbd00-61bf-11e9-8a6e-ac6d338a7db0.png)

![image](https://user-images.githubusercontent.com/17654862/56342400-956bdd00-61c0-11e9-9447-dad83b9e8076.png)

**Comment by alexdp1996** [comment]
#111
