### ISSUE TITLE
Kick user from team

### ISSUE THREAD

**Issue by katglin** [advancedWeb2018/TMS_cources_2019#110]
Nothing happens if I try to Kick a user (either manager or developer) with tasks assigned/created. If this is denied, I should get an appropriate message or the button should be disabled/hidden (the second is better).

I can't also kick a manager without tasks created and developer without tasks assigned.

**Comment by alexdp1996** [comment]
#111

**Comment by alexdp1996** [comment]
#111

**Comment by katglin** [comment]
Still can't
